config/routes.rb
Rails.application.routes.draw do
  # resources :customers do
  #   member do
  #     get 'customers/index'
  #     get 'customers/alphabetized'
  #     get 'customers/missing_email'
  #   end
  # end

  get 'customers/index'
  get 'customers/alphabetized'
  get 'customers/missing_email'
  root to: 'customers#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one_attached :image
  validates :full_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
     @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(:full_name)
  end

  def missing_email
    @customers = Customer.where("email_address LIKE ''")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
  <aside>

    <h3><%= customer.full_name %></h3>
    <% if customer.image.present? %>
      <p><%= image_tag customer.image.variant(resize_to_limit: [200, 200]).processed  %></p>
    <% end %>
  </aside>

app/views/customers/alphabetized.html.erb
<h1>this is all the customers in alphabetical order</h1>
<%= render @customers %>

app/views/customers/index.html.erb
<h1>this is all the customers</h1>
<%= render @customers %>

app/views/customers/missing_email.html.erb
<h1>this is all the customers with missing email address</h1>
<%= render @customers %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRM</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
   <%= link_to "all customners",  customers_index_path %>
    <%= link_to "alphabetized",  customers_alphabetized_path %>
  <%= link_to "missing email",  customers_missing_email_path %>
    <%= yield %>
  </body>
</html>